# https://quarto.org/docs/books/book-output.html
project:
  type: website
  output-dir: docs
  preview:
    port: 4201
  render:
    - "*.qmd"
    - "!notebooks"
  resources:
    - "notebooks"

website:
  title: "Code Camp"
  image: "img/CASA_Logo_no_text.png"
  repo-url: https://github.com/jreades/code-camp/
  repo-actions: [issue]
  favicon: "/img/favicon.ico"
  page-navigation: true
  reader-mode: true
  page-footer: 
    left: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 2022, J. Reades, F. Lopane, Z. Shabrina, J. Millington & M. Ferretti"
    center: "![](/img/favicon-16x16.png){.height:10px} Code Camp"
    right: 
      - icon: github
        href: https://github.com/jreades/code-camp/
      - icon: twitter 
        href: https://twitter.com/jreades
  navbar:
    background: primary
    search: true
    logo: "/img/CASA_Logo_no_text.png"
    collapse: true
    collapse-below: md
    left:
      - text: "Welcome"
        href: index.qmd
      - sidebar:setup
      - sidebar:lessons
      - text: "About"
        href: about.qmd

  sidebar:
    - id: setup
      title: "Setting Up"
      style: "docked"
      collapse-level: 2
      background: light
      contents:
        - text: "Getting Started"
          href: setup/index.qmd
        - text: "Computer Health Check"
          href: setup/health.qmd
        - text: "Python on your Computer"
          href: setup/install.qmd
        - text: "Python in the Cloud"
          href: setup/no_install.qmd
        - text: "Getting Help"
          href: help.qmd
    - id: lessons
      title: "Lessons"
      contents:
        - text: "Introduction"
          href: lessons/Introduction.qmd
        - text: "Background"
          href: lessons/Background.qmd
        - text: "The Basics"
          href: lessons/The_Basics.qmd
        - text: "Exceptions"
          href: lessons/Exceptions.qmd
        - text: "Writing Code"
          href: lessons/Writing_Code.qmd
        - text: "Boolean Logic"
          href: lessons/Boolean_Logic.qmd
        - text: "Recap 1"
          href: lessons/Recap_1.qmd
        - text: "Lists"
          href: lessons/Lists.qmd
        - text: "Dictionaries"
          href: lessons/Dicts.qmd
        - text: "Loops"
          href: lessons/Loops.qmd
        - text: "Recap 2"
          href: lessons/Recap_2.qmd
        - text: "Functions"
          href: lessons/Functions.qmd
        - text: "Packages"
          href: lessons/Packages.qmd
        - text: "Classes"
          href: lessons/Classes.qmd
        - text: "The Terminal"
          href: lessons/The_Terminal.qmd

#bibliography: bib/Readings.bib
#csl: bib/chicago-author-date.csl

highlight-style: pygments
format:
  html:
    theme: 
      - minty
      - css/web.scss
    code-copy: true
    code-link: true
    toc: true
    toc-title: "On this page"
    toc-depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: true
