## This is a Jupyter Notebook

There's no reason you'd know this yet, but the web page you're looking at is also known as a 'Jupyter notebook' -- it's why you can 'run' code as part of the web page. Check out this example by clicking in the box (next to the <span style="color:blue;font-family:monospace">In [ ]</span>) and hitting the 'run' button in the toolbar above or typing Ctrl+Return at the same time.

```python
#| geopyter: {Contributors: ['Michele Ferretti (https://github.com/miccferr)', 'Jon Reades (https://github.com/jreades)', 'James Millington (https://github.com/jamesdamillington)', 'Michele Ferretti (https://github.com/miccferr)', 'Jon Reades (https://github.com/jreades)', 'James Millington (https://github.com/jamesdamillington)'], git: {active_branch: master, author.name: Jon Reades, authored_date: '2017-06-05 16:12:59', committed_date: '2017-06-05 16:12:59', committer.name: Jon Reades, sha: 2fce1fab4c3c28acabee493a24302e5ee1e8a1eb}}
print('Hello world')
```

If all has gone well you should have seen `Hello world` appear on a line all on its own. That was Python code running in a notebook. Here's some more code:

```python
print( (1+2+3+4)/4 )
```

You can check that this gave you the right answer at the bottom of this page. 

Anyway, because of their history, some people will call these "iPython notebooks", others will call them "Jupyter notebooks", and some will just stick with "notebooks". They are all the same thing. 

Here's some more code to run as proof that this is actual code:

```python
#| scrolled: true
import sys
print(sys.version)
```

You don't need to understand all of that output, the point is that this is Python and we can do anything in a notebook that we would in a program.

