---
title: "Getting Started"
---

We've tried to keep Code Camp as simple as possible so that you can get started as quickly as possible. We will present you with some _options_ (and some _recommendations_), but it's up to you to choose the option that feels most natural to you. When classes begin we'll have some more strict requirements, but let's keep it simple for now.

## Prerequisites

Beyond finding a way to run Python code (see below), there are _no_ requirements or prerequisites for Code Camp. However, you might find it useful to complete the basic computer [health check](./health.qmd); that page also includes some *recommendations* if you are considering buying a new computer on which to run code. Once you know that your machine and operating system are up-to-date, you should install the [basic utilities](./base.qmd) that will enable you to complete installation of the programming environment.

## Running Python

You are welcome to run Code Camp code on your own computer (see: [install options](./install.qmd)), but you should look at the [no install options](./no_install.qmd). These are generally cloud-based options and are necessarily a 'second best' since limitations imposed by the provider mean that you probably won't be able to process the full data set with which we'll be working, but as a stop-gap they are perfectly useable.
