---
title: "Python in the Cloud"
---

When running code in the cloud, we are running it ‘remotely’, which means without installing anything on *your* computer. There are many other ways to run code, and that includes '[locally](install.qmd)' on your computer. But this is a great 'try before you buy' option.

::: {.callout-warning}

#### Internet Connectivity

You will be running code 'in the cloud' and so *will* need an internet-connected device to run the code. Also, note that in the cloud your work is less likely to be saved, but here the tasks are fairly simple so think of it as an opportunity to check your understanding.

:::

## In Your Browser

To make your life as easy as possible we use [Pyodide](https://pyodide.org/en/stable/), which allows you to run code in the your browser. For any of the lessons where there is code to run you will see a 'PYODIDE STATUS' that starts with `Initializing Python Packages` before changing to `Ready!` after a few seconds (depending on your Internet connection speed). 

Once Pyodide is ready you will have the opportunity to run (and edit!) code further down the page as demonstrated in this video:

{{< video https://youtu.be/nrYjHYEhCJU?si=Pn348cu8Fp7uaHln >}}

As far as we know Pyodide is fully compatible with any modern browser, but let us know if you experience problems.

## Google Colab {#sec-colab}

If you want to experiment further with what you've learned about Python then Google's [Colaboratory](https://colab.research.google.com/?) is the way to go. It will require a Google login, but offers a few benefits: you can save your code or search for and add other 'notebooks' (the way you will run code in Colab). As long as you don't mind having a Google account, it's probably the best way to get started.

Since there's nothing to install, here's a short video showing the process for running code in Google Colab. We've assumed that you already have a Google account, if not you'll need to set one up first:

{{< video https://youtu.be/pPGAfp0Oifg >}}


